name: Deploy Frontend

on:
  push:
    branches:
      - main  # Adjust to your branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'  # Adjust to your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Sync files
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avzr --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "18.199.92.253"
          REMOTE_USER: "ubuntu"
          TARGET: "/var/www/ht-frontend/"
